[build]
rustflags = [
    "-D", "warnings",
    "-D", "clippy::float_arithmetic",
]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]

[alias]
t = "test"
c = "clippy"
b = "build --release"
